apiVersion: v1
kind: Service
metadata:
  name: websrv-demo
  labels:
    app: k8s-node
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30080
  selector:
    app: k8s-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websrv-deploy
  labels:
    app: k8s-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-node
  template:
    metadata:
      labels:
        app: k8s-node
    spec:
      containers:
      - name: k8s-node
        image: demo-node-webserver:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
